## Configurations used for ctsm-mizuRoute

# Directories
case_dir       = '/glade/u/home/mizukami/proj/ctsm-mizuRoute/run_case'                #CESM case directory
archive_dir    = '/glade/campaign/cgd/tss/people/mizukami/ctsm-mizuRoute/archive'       #CESM archive directory
geospatial_dir = '/glade/campaign/cgd/tss/people/mizukami/ctsm-mizuRoute/geospatial'    #including geospatial data (gpkg, geotif)
ancillary_dir  = '/glade/u/home/mizukami/proj/ctsm-mizuRoute/postprocess+analysis//ancillary_data'
ref_flow_dir   = '/glade/u/home/mizukami/proj/ctsm-mizuRoute/obs'

# simulation periods
# now assuming all the simulations have the same periods and assuming start in January 1st and end in December 31st
syr = 1965   # analysis start year 
eyr = 1980   # analysis end yr

[rof_grid]
    [rof_grid.rHDMAlk]
        network='HDMA_lake'
        model='mizuroute'
        network_type='vector'
        domain_nc="None"
        flow_name='IRFroutedRunoff'
        runoff_name='basRunoff'
        color='xkcd:red'
    [rof_grid.rHDMAlk_dfw]
        network='HDMA_lake'
        model='mizuroute'
        network_type='vector'
        domain_nc="None"
        flow_name='DWroutedRunoff'
        runoff_name='basRunoff'
        color='xkcd:orange'
    [rof_grid.rHDMAlk_irrig]
        network='HDMA_lake'
        model='mizuroute'
        network_type='vector'
        domain_nc="None"
        flow_name='IRFroutedRunoff'
        runoff_name='basRunoff'
        color='xkcd:green'
    [rof_grid.rHDMAlk_irrig_unlimited]
        network='HDMA_lake'
        model='mizuroute'
        network_type='vector'
        domain_nc="None"
        flow_name='IRFroutedRunoff'
        runoff_name='basRunoff'
        color='xkcd:magenta'
    [rof_grid.rHDMAlk_irrig_groundwater]
        network='HDMA_lake'
        model='mizuroute'
        network_type='vector'
        domain_nc="None"
        flow_name='IRFroutedRunoff'
        runoff_name='basRunoff'
        color='xkcd:magenta'
    [rof_grid.rHDMA]
        network='HDMA'
        model='mizuroute'
        network_type='vector'
        domain_nc="None"
        flow_name='IRFroutedRunoff'
        runoff_name='basRunoff'
        color='xkcd:blue'
    [rof_grid.rMERIT]
        network='MERIT_Hydro'
        model='mizuroute'
        network_type='vector'
        domain_nc="None"
        flow_name='IRFroutedRunoff'
        runoff_name='basRunoff'
        color='xkcd:green'
    [rof_grid.f09_f09]
         network='mosart'
         model='mizuroute'
         network_type='vector'
         domain_nc='None'
         flow_name='IRFroutedRunoff'
         runoff_name='basRunoff'
         color='xkcd:green'
    [rof_grid.f09_f09_mosart]
         network='mosart'
         model='mosart'
         network_type='grid'
         domain_nc='mosart0.5_domain.nc'
         flow_name='RIVER_DISCHARGE_OVER_LAND_LIQ'
         runoff_name='None'
         color='xkcd:grey'


# riiver line geopackage metadata
# sub-key is network name
[reach_gpkg]
    [reach_gpkg.HDMA]     # global HDMA
        file_name='hdma_global_stream.gpkg'
        id_name='seg_id'
        down_id_name='Tosegment'
        
    [reach_gpkg.HDMA_lake] # global HDMA lake
        file_name='hdma_global_stream.gpkg'
        id_name='seg_id'
        down_id_name='Tosegment'

    [reach_gpkg.MERIT_Hydro]  # global MERIT
        file_name='rivEndMERIT_simplified_0003.gpkg'
        id_name='COMID'
        down_id_name='NextDownID'
        
    [reach_gpkg.mosart] # global MOSART 0.5
        file_name='mosart0.5_stream.gpkg'          
        id_name='seg_id'
        down_id_name='Tosegment'

# catchment geopackage metadata
# sub-key is network name
[catch_gpkg]
    [catch_gpkg.HDMA]  # global HDMA
        file_name='hdma_global_catch_v2_0.01.gpkg'       
        id_name='hruid'

    [catch_gpkg.HDMA_lake] # global HDMA lake
        file_name='hdma_hydrolake_global_catch_v1_0.01.gpkg'
        id_name='ID'
        
    [catch_gpkg.MERIT_Hydro] # global MERIT
        file_name='catEndoMERIT.gpkg'
        id_name='hruid'
        
    [catch_gpkg.mosart] # global MOSART 0.5
        file_name='mosart0.5_global_land.gpkg'
        id_name='hru_id'

# river network data (mizuRoute format, augumented one)
# sub-key is network name
[river_network]
    [river_network.HDMA]  # global HDMA
        file_name='ntopo_HDMA.v2.aug.nc'
        reach_ID ='seg_id'

    [river_network.HDMA_lake] # global HDMA lake
        file_name='Network_topology_HDMA_HydroLake_v3_aug.nc'
        reach_ID ='seg_id'
        
    [river_network.MERIT_Hydro] # global MERIT
        file_name='ntopo_MERIT_Hydro_v1.aug.nc'
        reach_ID ='seg_id'
        
    [river_network.mosart] # global MOSART 0.5
        file_name='mizuRoute_MOSART_Global_half_20161105a_aug.nc'       # MOSART simulation use [-180 180] grids
        #file_name='mizuRoute_MOSART_Global_half_20161105a_360_aug.nc'  # mizuRoute simulation used [0 360] based network and mesh. In the future should use [-180 180] grid (above) for simulation
        reach_ID ='seg_id'  
